# Generated by Django 5.2.4 on 2025-09-19 18:33

import cloudinary_storage.storage
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, default='', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='payments/qr/')),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sponsor_id', models.CharField(max_length=255)),
                ('placement_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('payment_type', models.CharField(choices=[('GPay', 'GPay'), ('PhonePe', 'PhonePe'), ('PhonePay', 'PhonePay'), ('Paytm', 'Paytm'), ('Other', 'Other')], default='razorpay', max_length=20)),
                ('upi_number', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('sponsor_id', models.CharField(max_length=255)),
                ('placement_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('pincode', models.CharField(max_length=10)),
                ('payment_type', models.CharField(choices=[('Razorpay', 'Razorpay'), ('GPay', 'GPay'), ('PhonePe', 'PhonePe'), ('PhonePay', 'PhonePay'), ('Paytm', 'Paytm'), ('Other', 'Other')], max_length=20)),
                ('upi_number', models.CharField(max_length=50)),
                ('date_of_joining', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin_user', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('receipt', models.FileField(blank=True, null=True, upload_to='payments/')),
                ('registration_data', models.TextField(blank=True, null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=20)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('upi_number', models.CharField(max_length=50)),
                ('upi_type', models.CharField(choices=[('GPay', 'GPay'), ('PhonePe', 'PhonePe'), ('PhonePay', 'PhonePay'), ('Paytm', 'Paytm'), ('Other', 'Other')], max_length=20)),
                ('qr_code', models.ImageField(blank=True, default='', null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='user_qr_codes/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
