# Generated by Django 5.2.4 on 2025-09-20 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='payment_type',
            field=models.CharField(choices=[('GPay', 'GPay'), ('PhonePe', 'PhonePe'), ('PhonePay', 'PhonePay'), ('Paytm', 'Paytm'), ('Other', 'Other')], max_length=20),
        ),
    ]
