# Generated by Django 5.2.4 on 2025-09-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_payment_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sponsor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
